+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the database config.'
+ message='Start to prepare the database config.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the database config.'
Tue May 30 14:33:31 2023 - INFO  - Start to prepare the database config.
+ DNF_INSTALL 'clamav clamav-server'
+ pkgs='clamav clamav-server'
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs 'clamav clamav-server' --node 1 --tempfile ''
+ tmpfile2=/tmp/tmptzlhd_e8
+ '[' -z '' ']'
+ tmpfile=/tmp/tmptzlhd_e8
+ mv /etc/clamd.d/scan.conf /etc/clamd.d/scan.conf.bak
+ echo 'LogFile /var/log/clamd.scan
        LogFileMaxSize 2M
        LogTime yes
        PidFile /run/clamd.scan/clamd.pid
        DatabaseDirectory /var/lib/clamav
        TCPAddr 0.0.0.0
        TCPSocket 3310'
+ systemctl restart clamd@scan.service
Job for clamd@scan.service failed because a timeout was exceeded.
See "systemctl status clamd@scan.service" and "journalctl -xeu clamd@scan.service" for details.
+ mkdir move_infected_dir copy_infected_dir
+ echo '/var/lib/clamav
/opt'
+ LOG_INFO 'End to prepare the database config.'
+ message='End to prepare the database config.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the database config.'
Tue May 30 14:46:50 2023 - INFO  - End to prepare the database config.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Tue May 30 14:46:52 2023 - INFO  - Start to run test.
+ clamdscan -v -l clamdscan_log /var/lib/clamav
ERROR: Could not connect to clamd on 0.0.0.0: Connection refused
+ CHECK_RESULT 2 0 0 'Check clamdscan  -v -l clamdscan_log /var/lib/clamav failed.'
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log='Check clamdscan  -v -l clamdscan_log /var/lib/clamav failed.'
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n 'Check clamdscan  -v -l clamdscan_log /var/lib/clamav failed.'
+ LOG_ERROR 'Check clamdscan  -v -l clamdscan_log /var/lib/clamav failed.'
+ message='Check clamdscan  -v -l clamdscan_log /var/lib/clamav failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Check clamdscan  -v -l clamdscan_log /var/lib/clamav failed.'
Tue May 30 14:46:54 2023 - ERROR - Check clamdscan  -v -l clamdscan_log /var/lib/clamav failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_clamav_clamdscan_scan.sh line 45'
+ message='oe_test_clamav_clamdscan_scan.sh line 45'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_clamav_clamdscan_scan.sh line 45'
Tue May 30 14:46:56 2023 - ERROR - oe_test_clamav_clamdscan_scan.sh line 45
+ '[' 0 -eq 1 ']'
+ return 0
+ clamdscan --quiet /var/lib/clamav
ERROR: Could not connect to clamd on 0.0.0.0: Connection refused
+ CHECK_RESULT 2 0 0 'Check clamdscan --quiet failed.'
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log='Check clamdscan --quiet failed.'
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n 'Check clamdscan --quiet failed.'
+ LOG_ERROR 'Check clamdscan --quiet failed.'
+ message='Check clamdscan --quiet failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Check clamdscan --quiet failed.'
Tue May 30 14:46:58 2023 - ERROR - Check clamdscan --quiet failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_clamav_clamdscan_scan.sh line 47'
+ message='oe_test_clamav_clamdscan_scan.sh line 47'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_clamav_clamdscan_scan.sh line 47'
Tue May 30 14:46:59 2023 - ERROR - oe_test_clamav_clamdscan_scan.sh line 47
+ '[' 0 -eq 1 ']'
+ return 0
+ clamdscan --remove /var/lib/clamav
ERROR: Could not connect to clamd on 0.0.0.0: Connection refused
+ CHECK_RESULT 2 0 0 'Check clamdscan --remove failed.'
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log='Check clamdscan --remove failed.'
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n 'Check clamdscan --remove failed.'
+ LOG_ERROR 'Check clamdscan --remove failed.'
+ message='Check clamdscan --remove failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Check clamdscan --remove failed.'
Tue May 30 14:47:01 2023 - ERROR - Check clamdscan --remove failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_clamav_clamdscan_scan.sh line 49'
+ message='oe_test_clamav_clamdscan_scan.sh line 49'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_clamav_clamdscan_scan.sh line 49'
Tue May 30 14:47:03 2023 - ERROR - oe_test_clamav_clamdscan_scan.sh line 49
+ '[' 0 -eq 1 ']'
+ return 0
+ clamdscan --move=move_infected_dir /var/lib/clamav
ERROR: Could not connect to clamd on 0.0.0.0: Connection refused
+ CHECK_RESULT 2 0 0 'Check clamdscan --move failed.'
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log='Check clamdscan --move failed.'
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n 'Check clamdscan --move failed.'
+ LOG_ERROR 'Check clamdscan --move failed.'
+ message='Check clamdscan --move failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Check clamdscan --move failed.'
Tue May 30 14:47:05 2023 - ERROR - Check clamdscan --move failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_clamav_clamdscan_scan.sh line 51'
+ message='oe_test_clamav_clamdscan_scan.sh line 51'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_clamav_clamdscan_scan.sh line 51'
Tue May 30 14:47:07 2023 - ERROR - oe_test_clamav_clamdscan_scan.sh line 51
+ '[' 0 -eq 1 ']'
+ return 0
+ clamdscan --copy=copy_infected_dir /var/lib/clamav
ERROR: Could not connect to clamd on 0.0.0.0: Connection refused
+ CHECK_RESULT 2 0 0 'Check clamdscan --copy failed.'
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log='Check clamdscan --copy failed.'
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n 'Check clamdscan --copy failed.'
+ LOG_ERROR 'Check clamdscan --copy failed.'
+ message='Check clamdscan --copy failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Check clamdscan --copy failed.'
Tue May 30 14:47:08 2023 - ERROR - Check clamdscan --copy failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_clamav_clamdscan_scan.sh line 53'
+ message='oe_test_clamav_clamdscan_scan.sh line 53'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_clamav_clamdscan_scan.sh line 53'
Tue May 30 14:47:10 2023 - ERROR - oe_test_clamav_clamdscan_scan.sh line 53
+ '[' 0 -eq 1 ']'
+ return 0
+ clamdscan --config-file=/etc/clamd.d/scan.conf /var/lib/clamav
ERROR: Could not connect to clamd on 0.0.0.0: Connection refused
+ CHECK_RESULT 2 0 0 'Check clamdscan --config-file failed.'
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log='Check clamdscan --config-file failed.'
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n 'Check clamdscan --config-file failed.'
+ LOG_ERROR 'Check clamdscan --config-file failed.'
+ message='Check clamdscan --config-file failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Check clamdscan --config-file failed.'
Tue May 30 14:47:12 2023 - ERROR - Check clamdscan --config-file failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_clamav_clamdscan_scan.sh line 55'
+ message='oe_test_clamav_clamdscan_scan.sh line 55'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_clamav_clamdscan_scan.sh line 55'
Tue May 30 14:47:14 2023 - ERROR - oe_test_clamav_clamdscan_scan.sh line 55
+ '[' 0 -eq 1 ']'
+ return 0
+ clamdscan -i /var/lib/clamav
ERROR: Could not connect to clamd on 0.0.0.0: Connection refused
+ CHECK_RESULT 2 0 0 'Check clamdscan -i failed.'
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log='Check clamdscan -i failed.'
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n 'Check clamdscan -i failed.'
+ LOG_ERROR 'Check clamdscan -i failed.'
+ message='Check clamdscan -i failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Check clamdscan -i failed.'
Tue May 30 14:47:16 2023 - ERROR - Check clamdscan -i failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_clamav_clamdscan_scan.sh line 57'
+ message='oe_test_clamav_clamdscan_scan.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_clamav_clamdscan_scan.sh line 57'
Tue May 30 14:47:17 2023 - ERROR - oe_test_clamav_clamdscan_scan.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ clamdscan --no-summary /var/lib/clamav
ERROR: Could not connect to clamd on 0.0.0.0: Connection refused
+ CHECK_RESULT 2 0 0 'Check clamdscan --no-summary failed.'
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log='Check clamdscan --no-summary failed.'
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n 'Check clamdscan --no-summary failed.'
+ LOG_ERROR 'Check clamdscan --no-summary failed.'
+ message='Check clamdscan --no-summary failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Check clamdscan --no-summary failed.'
Tue May 30 14:47:19 2023 - ERROR - Check clamdscan --no-summary failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_clamav_clamdscan_scan.sh line 59'
+ message='oe_test_clamav_clamdscan_scan.sh line 59'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_clamav_clamdscan_scan.sh line 59'
Tue May 30 14:47:21 2023 - ERROR - oe_test_clamav_clamdscan_scan.sh line 59
+ '[' 0 -eq 1 ']'
+ return 0
+ clamdscan --file-list=testfile
ERROR: Could not connect to clamd on 0.0.0.0: Connection refused
ERROR: Could not connect to clamd on 0.0.0.0: Connection refused
+ CHECK_RESULT 2 0 0 'Check clamdscan --file-list failed.'
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log='Check clamdscan --file-list failed.'
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n 'Check clamdscan --file-list failed.'
+ LOG_ERROR 'Check clamdscan --file-list failed.'
+ message='Check clamdscan --file-list failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Check clamdscan --file-list failed.'
Tue May 30 14:47:23 2023 - ERROR - Check clamdscan --file-list failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_clamav_clamdscan_scan.sh line 61'
+ message='oe_test_clamav_clamdscan_scan.sh line 61'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_clamav_clamdscan_scan.sh line 61'
Tue May 30 14:47:25 2023 - ERROR - oe_test_clamav_clamdscan_scan.sh line 61
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Tue May 30 14:47:26 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 9
+ test 9 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Tue May 30 14:47:28 2023 - ERROR - failed to execute the case.
+ exit 9
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Tue May 30 14:47:30 2023 - INFO  - Start to restore the test environment.
+ rm -rf /etc/clamd.d/scan.conf clamdscan_log move_infected_dir copy_infected_dir testfile
+ mv /etc/clamd.d/scan.conf.bak /etc/clamd.d/scan.conf
+ systemctl restart clamd@scan.service
Job for clamd@scan.service failed because the control process exited with error code.
See "systemctl status clamd@scan.service" and "journalctl -xeu clamd@scan.service" for details.
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmptzlhd_e8 ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmptzlhd_e8
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Tue May 30 14:48:49 2023 - INFO  - End to restore the test environment.
