+ source ../common_lib/fsio_lib.sh
++ source /root/mugen-riscv/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
++ export 'FS_TYPE=ext3 ext4 xfs'
++ FS_TYPE='ext3 ext4 xfs'
++ export LANG=en_US.UTF-8
++ LANG=en_US.UTF-8
++ REMOVE_VG
++ vggroup=
++ [[ '' != '' ]]
+++ df -T
+++ grep test_vggroup
+++ awk '{print $7}'
++ mounted=
++ [[ '' != '' ]]
++ lsblk
++ grep test_vggroup
++ [[ 1 -eq 0 ]]
++ rm -rf '/tmp/point*'
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the database config.'
+ message='Start to prepare the database config.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the database config.'
Mon Jul 24 06:55:10 2023 - INFO  - Start to prepare the database config.
++ date +%Y%m%d%H%M%S
+ cur_date=20230724065510
++ CREATE_VG
+++ date +%Y%m%d%H%M%S
++ cur_date=20230724065510
+++ lsblk
+++ grep disk
+++ awk '{print $1}'
+++ tail -n 1
++ free_disk=vda
++ disk_name=/dev/vda
++ pvcreate /dev/vda -f
++ [[ 5 -eq 0 ]]
+++ pvcreate /dev/vda
+++ grep test_vggroup
+++ cut -d '"' -f 4
++ vggroup=
++ printf
printf: usage: printf [-v var] format [arguments]
+ vggroup=
+ lv1=test_lv120230724065510
+ lv2=test_lv220230724065510
+ lv3=test_lv320230724065510
+ lvcreate -n test_lv120230724065510 -L 2G -y
  No command with matching syntax recognised.  Run 'lvcreate --help' for more information.
  Nearest similar command has syntax:
+ lvcreate -n test_lv220230724065510 -L 2G -y
  No command with matching syntax recognised.  Run 'lvcreate --help' for more information.
  Nearest similar command has syntax:
+ lvcreate -n test_lv320230724065510 -L 2G -y
  No command with matching syntax recognised.  Run 'lvcreate --help' for more information.
  Nearest similar command has syntax:
+ mkfs.ext3 /dev//test_lv120230724065510
mke2fs 1.46.5 (30-Dec-2021)
The file /dev//test_lv120230724065510 does not exist and no size was specified.
+ mkfs.ext4 /dev//test_lv220230724065510
mke2fs 1.46.5 (30-Dec-2021)
The file /dev//test_lv220230724065510 does not exist and no size was specified.
+ mkfs.xfs /dev//test_lv320230724065510
Error accessing specified device /dev//test_lv320230724065510: No such file or directory
Usage: mkfs.xfs
/* blocksize */		[-b size=num]
/* config file */	[-c options=xxx]
/* metadata */		[-m crc=0|1,finobt=0|1,uuid=xxx,rmapbt=0|1,reflink=0|1,
			    inobtcount=0|1,bigtime=0|1]
/* data subvol */	[-d agcount=n,agsize=n,file,name=xxx,size=num,
			    (sunit=value,swidth=value|su=num,sw=num|noalign),
			    sectsize=num
/* force overwrite */	[-f]
/* inode size */	[-i perblock=n|size=num,maxpct=n,attr=0|1|2,
			    projid32bit=0|1,sparse=0|1,nrext64=0|1]
/* no discard */	[-K]
/* log subvol */	[-l agnum=n,internal,size=num,logdev=xxx,version=n
			    sunit=value|su=num,sectsize=num,lazy-count=0|1]
/* label */		[-L label (maximum 12 characters)]
/* naming */		[-n size=num,version=2|ci,ftype=0|1]
/* no-op info only */	[-N]
/* prototype file */	[-p fname]
/* quiet */		[-q]
/* realtime subvol */	[-r extsize=num,size=num,rtdev=xxx]
/* sectorsize */	[-s size=num]
/* version */		[-V]
			devicename
<devicename> is required unless -d name=xxx is given.
<num> is xxx (bytes), xxxs (sectors), xxxb (fs blocks), xxxk (xxx KiB),
      xxxm (xxx MiB), xxxg (xxx GiB), xxxt (xxx TiB) or xxxp (xxx PiB).
<value> is xxx (512 byte blocks).
+ point=/mnt/point20230724065510
+ mkdir /mnt/point20230724065510
+ mount /dev//test_lv120230724065510 /mnt/point20230724065510
mount: /mnt/point20230724065510: special device /dev//test_lv120230724065510 does not exist.
+ echo 'test ext3'
+ LOG_INFO 'Finish to prepare the database config.'
+ message='Finish to prepare the database config.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish to prepare the database config.'
Mon Jul 24 06:55:12 2023 - INFO  - Finish to prepare the database config.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Mon Jul 24 06:55:12 2023 - INFO  - Start to run test.
+ mount /dev//test_lv220230724065510 /mnt/point20230724065510
mount: /mnt/point20230724065510: special device /dev//test_lv220230724065510 does not exist.
+ CHECK_RESULT 32 0 0 'Mount ext4 on /mnt/point20230724065510 failed.'
+ actual_result=32
+ expect_result=0
+ mode=0
+ error_log='Mount ext4 on /mnt/point20230724065510 failed.'
+ '[' -z 32 ']'
+ '[' 0 -eq 0 ']'
+ test 32x '!=' 0x
+ test -n 'Mount ext4 on /mnt/point20230724065510 failed.'
+ LOG_ERROR 'Mount ext4 on /mnt/point20230724065510 failed.'
+ message='Mount ext4 on /mnt/point20230724065510 failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Mount ext4 on /mnt/point20230724065510 failed.'
Mon Jul 24 06:55:13 2023 - ERROR - Mount ext4 on /mnt/point20230724065510 failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_mount_remount.sh line 44'
+ message='oe_test_FSIO_mount_remount.sh line 44'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_mount_remount.sh line 44'
Mon Jul 24 06:55:13 2023 - ERROR - oe_test_FSIO_mount_remount.sh line 44
+ return 0
+ echo 'test ext4'
+ df -T
+ grep /mnt/point20230724065510
+ grep ext4
+ CHECK_RESULT 1 0 0 'The fs type of /mnt/point20230724065510 is not ext4.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The fs type of /mnt/point20230724065510 is not ext4.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The fs type of /mnt/point20230724065510 is not ext4.'
+ LOG_ERROR 'The fs type of /mnt/point20230724065510 is not ext4.'
+ message='The fs type of /mnt/point20230724065510 is not ext4.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'The fs type of /mnt/point20230724065510 is not ext4.'
Mon Jul 24 06:55:14 2023 - ERROR - The fs type of /mnt/point20230724065510 is not ext4.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_mount_remount.sh line 47'
+ message='oe_test_FSIO_mount_remount.sh line 47'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_mount_remount.sh line 47'
Mon Jul 24 06:55:14 2023 - ERROR - oe_test_FSIO_mount_remount.sh line 47
+ return 0
+ mount /dev//test_lv320230724065510 /mnt/point20230724065510
mount: /mnt/point20230724065510: special device /dev//test_lv320230724065510 does not exist.
+ CHECK_RESULT 32 0 0 'Mount xfs on /mnt/point20230724065510 failed.'
+ actual_result=32
+ expect_result=0
+ mode=0
+ error_log='Mount xfs on /mnt/point20230724065510 failed.'
+ '[' -z 32 ']'
+ '[' 0 -eq 0 ']'
+ test 32x '!=' 0x
+ test -n 'Mount xfs on /mnt/point20230724065510 failed.'
+ LOG_ERROR 'Mount xfs on /mnt/point20230724065510 failed.'
+ message='Mount xfs on /mnt/point20230724065510 failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Mount xfs on /mnt/point20230724065510 failed.'
Mon Jul 24 06:55:14 2023 - ERROR - Mount xfs on /mnt/point20230724065510 failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_mount_remount.sh line 49'
+ message='oe_test_FSIO_mount_remount.sh line 49'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_mount_remount.sh line 49'
Mon Jul 24 06:55:15 2023 - ERROR - oe_test_FSIO_mount_remount.sh line 49
+ return 0
+ echo 'test xfs'
+ df -T
+ grep /mnt/point20230724065510
+ grep xfs
+ CHECK_RESULT 1 0 0 'The fs type of /mnt/point20230724065510 is not xfs.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The fs type of /mnt/point20230724065510 is not xfs.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The fs type of /mnt/point20230724065510 is not xfs.'
+ LOG_ERROR 'The fs type of /mnt/point20230724065510 is not xfs.'
+ message='The fs type of /mnt/point20230724065510 is not xfs.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'The fs type of /mnt/point20230724065510 is not xfs.'
Mon Jul 24 06:55:15 2023 - ERROR - The fs type of /mnt/point20230724065510 is not xfs.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_mount_remount.sh line 52'
+ message='oe_test_FSIO_mount_remount.sh line 52'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_mount_remount.sh line 52'
Mon Jul 24 06:55:16 2023 - ERROR - oe_test_FSIO_mount_remount.sh line 52
+ return 0
+ test -f /mnt/point20230724065510/testxfs
+ CHECK_RESULT 0 0 0 'The testxfs doesn'\''t exist.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='The testxfs doesn'\''t exist.'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ test -f /mnt/point20230724065510/testext4
+ CHECK_RESULT 0 1 0 'The testext4 exists unexpectly.'
+ actual_result=0
+ expect_result=1
+ mode=0
+ error_log='The testext4 exists unexpectly.'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 1x
+ test -n 'The testext4 exists unexpectly.'
+ LOG_ERROR 'The testext4 exists unexpectly.'
+ message='The testext4 exists unexpectly.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'The testext4 exists unexpectly.'
Mon Jul 24 06:55:16 2023 - ERROR - The testext4 exists unexpectly.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_mount_remount.sh line 56'
+ message='oe_test_FSIO_mount_remount.sh line 56'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_mount_remount.sh line 56'
Mon Jul 24 06:55:17 2023 - ERROR - oe_test_FSIO_mount_remount.sh line 56
+ return 0
+ test -f /mnt/point20230724065510/testext3
+ CHECK_RESULT 0 1 0 'The testext3 exists unexpectly.'
+ actual_result=0
+ expect_result=1
+ mode=0
+ error_log='The testext3 exists unexpectly.'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 1x
+ test -n 'The testext3 exists unexpectly.'
+ LOG_ERROR 'The testext3 exists unexpectly.'
+ message='The testext3 exists unexpectly.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'The testext3 exists unexpectly.'
Mon Jul 24 06:55:17 2023 - ERROR - The testext3 exists unexpectly.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_mount_remount.sh line 58'
+ message='oe_test_FSIO_mount_remount.sh line 58'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_mount_remount.sh line 58'
Mon Jul 24 06:55:18 2023 - ERROR - oe_test_FSIO_mount_remount.sh line 58
+ return 0
+ umount /mnt/point20230724065510
umount: /mnt/point20230724065510: not mounted.
+ df -T
+ grep /mnt/point20230724065510
+ grep ext4
+ CHECK_RESULT 1 0 0 'The fs type of /mnt/point20230724065510 is not ext4.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The fs type of /mnt/point20230724065510 is not ext4.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The fs type of /mnt/point20230724065510 is not ext4.'
+ LOG_ERROR 'The fs type of /mnt/point20230724065510 is not ext4.'
+ message='The fs type of /mnt/point20230724065510 is not ext4.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'The fs type of /mnt/point20230724065510 is not ext4.'
Mon Jul 24 06:55:18 2023 - ERROR - The fs type of /mnt/point20230724065510 is not ext4.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_mount_remount.sh line 61'
+ message='oe_test_FSIO_mount_remount.sh line 61'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_mount_remount.sh line 61'
Mon Jul 24 06:55:18 2023 - ERROR - oe_test_FSIO_mount_remount.sh line 61
+ return 0
+ test -f /mnt/point20230724065510/testext4
+ CHECK_RESULT 0 0 0 'The testext4 doesn'\''t exist.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='The testext4 doesn'\''t exist.'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ test -f /mnt/point20230724065510/testxfs
+ CHECK_RESULT 0 1 0 'The testxfs exists unexpectly.'
+ actual_result=0
+ expect_result=1
+ mode=0
+ error_log='The testxfs exists unexpectly.'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 1x
+ test -n 'The testxfs exists unexpectly.'
+ LOG_ERROR 'The testxfs exists unexpectly.'
+ message='The testxfs exists unexpectly.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'The testxfs exists unexpectly.'
Mon Jul 24 06:55:19 2023 - ERROR - The testxfs exists unexpectly.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_mount_remount.sh line 65'
+ message='oe_test_FSIO_mount_remount.sh line 65'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_mount_remount.sh line 65'
Mon Jul 24 06:55:19 2023 - ERROR - oe_test_FSIO_mount_remount.sh line 65
+ return 0
+ test -f /mnt/point20230724065510/testext3
+ CHECK_RESULT 0 1 0 'The testext3 exists unexpectly.'
+ actual_result=0
+ expect_result=1
+ mode=0
+ error_log='The testext3 exists unexpectly.'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 1x
+ test -n 'The testext3 exists unexpectly.'
+ LOG_ERROR 'The testext3 exists unexpectly.'
+ message='The testext3 exists unexpectly.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'The testext3 exists unexpectly.'
Mon Jul 24 06:55:20 2023 - ERROR - The testext3 exists unexpectly.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_mount_remount.sh line 67'
+ message='oe_test_FSIO_mount_remount.sh line 67'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_mount_remount.sh line 67'
Mon Jul 24 06:55:20 2023 - ERROR - oe_test_FSIO_mount_remount.sh line 67
+ return 0
+ umount /mnt/point20230724065510
umount: /mnt/point20230724065510: not mounted.
+ df -T
+ grep /mnt/point20230724065510
+ grep ext3
+ CHECK_RESULT 1 0 0 'The fs type of /mnt/point20230724065510 is not ext3.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The fs type of /mnt/point20230724065510 is not ext3.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The fs type of /mnt/point20230724065510 is not ext3.'
+ LOG_ERROR 'The fs type of /mnt/point20230724065510 is not ext3.'
+ message='The fs type of /mnt/point20230724065510 is not ext3.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'The fs type of /mnt/point20230724065510 is not ext3.'
Mon Jul 24 06:55:21 2023 - ERROR - The fs type of /mnt/point20230724065510 is not ext3.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_mount_remount.sh line 70'
+ message='oe_test_FSIO_mount_remount.sh line 70'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_mount_remount.sh line 70'
Mon Jul 24 06:55:21 2023 - ERROR - oe_test_FSIO_mount_remount.sh line 70
+ return 0
+ test -f /mnt/point20230724065510/testext3
+ CHECK_RESULT 0 0 0 'The testext3 doesn'\''t exist.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='The testext3 doesn'\''t exist.'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ test -f /mnt/point20230724065510/testxfs
+ CHECK_RESULT 0 1 0 'The testxfs exists unexpectly.'
+ actual_result=0
+ expect_result=1
+ mode=0
+ error_log='The testxfs exists unexpectly.'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 1x
+ test -n 'The testxfs exists unexpectly.'
+ LOG_ERROR 'The testxfs exists unexpectly.'
+ message='The testxfs exists unexpectly.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'The testxfs exists unexpectly.'
Mon Jul 24 06:55:22 2023 - ERROR - The testxfs exists unexpectly.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_mount_remount.sh line 74'
+ message='oe_test_FSIO_mount_remount.sh line 74'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_mount_remount.sh line 74'
Mon Jul 24 06:55:22 2023 - ERROR - oe_test_FSIO_mount_remount.sh line 74
+ return 0
+ test -f /mnt/point20230724065510/testext4
+ CHECK_RESULT 0 1 0 'The testext4 exists unexpectly.'
+ actual_result=0
+ expect_result=1
+ mode=0
+ error_log='The testext4 exists unexpectly.'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 1x
+ test -n 'The testext4 exists unexpectly.'
+ LOG_ERROR 'The testext4 exists unexpectly.'
+ message='The testext4 exists unexpectly.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'The testext4 exists unexpectly.'
Mon Jul 24 06:55:23 2023 - ERROR - The testext4 exists unexpectly.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_mount_remount.sh line 76'
+ message='oe_test_FSIO_mount_remount.sh line 76'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_mount_remount.sh line 76'
Mon Jul 24 06:55:23 2023 - ERROR - oe_test_FSIO_mount_remount.sh line 76
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Mon Jul 24 06:55:23 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 12
+ test 12 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Mon Jul 24 06:55:24 2023 - ERROR - failed to execute the case.
+ exit 12
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Mon Jul 24 06:55:24 2023 - INFO  - Start to restore the test environment.
+ umount /mnt/point20230724065510
umount: /mnt/point20230724065510: not mounted.
+ rm -rf /mnt/point20230724065510
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Mon Jul 24 06:55:25 2023 - INFO  - End to restore the test environment.
