+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environment preparation.'
+ message='Start environment preparation.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start environment preparation.'
Thu May 25 17:59:58 2023 - INFO  - Start environment preparation.
+ mkdir -p /tmp/test /tmp/person
+ path1=/tmp/test
+ path2=/tmp/person
+ cat
+ cat
+ cat
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Thu May 25 17:59:59 2023 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start testing...'
+ message='Start testing...'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start testing...'
Thu May 25 17:59:59 2023 - INFO  - Start testing...
+ cd /tmp/person
+ gcc person.cpp -fpic -shared -o libperson.so
oe_test_gcc_002.sh: line 61: gcc: command not found
+ test -f /tmp/person/libperson.so
+ CHECK_RESULT 1 0 0 'libperson file fails'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='libperson file fails'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'libperson file fails'
+ LOG_ERROR 'libperson file fails'
+ message='libperson file fails'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'libperson file fails'
Thu May 25 18:00:00 2023 - ERROR - libperson file fails
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_gcc_002.sh line 63'
+ message='oe_test_gcc_002.sh line 63'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_gcc_002.sh line 63'
Thu May 25 18:00:00 2023 - ERROR - oe_test_gcc_002.sh line 63
+ '[' 0 -eq 1 ']'
+ return 0
+ cd /tmp/test
+ g++ main.cpp -o main -I../person -L../person -lperson
oe_test_gcc_002.sh: line 64: g++: command not found
+ test -f /tmp/test/main
+ CHECK_RESULT 1 0 0 'main file fails'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='main file fails'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'main file fails'
+ LOG_ERROR 'main file fails'
+ message='main file fails'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'main file fails'
Thu May 25 18:00:00 2023 - ERROR - main file fails
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_gcc_002.sh line 66'
+ message='oe_test_gcc_002.sh line 66'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_gcc_002.sh line 66'
Thu May 25 18:00:01 2023 - ERROR - oe_test_gcc_002.sh line 66
+ '[' 0 -eq 1 ']'
+ return 0
+ export LD_LIBRARY_PATH=../person
+ LD_LIBRARY_PATH=../person
+ ./main
oe_test_gcc_002.sh: line 68: ./main: No such file or directory
+ grep 'test g++' /tmp/test/main.txt
+ CHECK_RESULT 1 0 0 'main.txt file fails'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='main.txt file fails'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'main.txt file fails'
+ LOG_ERROR 'main.txt file fails'
+ message='main.txt file fails'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'main.txt file fails'
Thu May 25 18:00:01 2023 - ERROR - main.txt file fails
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_gcc_002.sh line 70'
+ message='oe_test_gcc_002.sh line 70'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_gcc_002.sh line 70'
Thu May 25 18:00:02 2023 - ERROR - oe_test_gcc_002.sh line 70
+ '[' 0 -eq 1 ']'
+ return 0
+ ldd main
ldd: ./main: No such file or directory
+ grep linux-vdso.so.1 /tmp/test/lddmain.txt
+ CHECK_RESULT 1 0 0 'lddmain.txt file fails'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='lddmain.txt file fails'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'lddmain.txt file fails'
+ LOG_ERROR 'lddmain.txt file fails'
+ message='lddmain.txt file fails'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'lddmain.txt file fails'
Thu May 25 18:00:02 2023 - ERROR - lddmain.txt file fails
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_gcc_002.sh line 73'
+ message='oe_test_gcc_002.sh line 73'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_gcc_002.sh line 73'
Thu May 25 18:00:02 2023 - ERROR - oe_test_gcc_002.sh line 73
+ '[' 0 -eq 1 ']'
+ return 0
+ CASE_RESULT 0
+ case_re=0
+ test -z 4
+ test 4 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Thu May 25 18:00:03 2023 - ERROR - failed to execute the case.
+ exit 4
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Thu May 25 18:00:03 2023 - INFO  - start environment cleanup.
+ rm -rf /tmp/test /tmp/person
+ LOG_INFO 'Finish environment cleanup!'
+ message='Finish environment cleanup!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup!'
Thu May 25 18:00:03 2023 - INFO  - Finish environment cleanup!
