+ source ../common/storage_disk_lib.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start loading data!'
+ message='Start loading data!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start loading data!'
Fri Apr 28 06:58:41 2023 - INFO  - Start loading data!
+ check_free_disk
++ TEST_DISK
++ id=1
++ python3 /root/mugen/libs/locallibs/get_test_device.py --device disk --node 1
+ disks=vdb
+ disk_list=($disks)
+ local_disk=vdb
+ local_disk1=
+ local_disk2=
+ local_disk3=
+ pvcreate -y /dev/
  No device found for /dev/.
+ vgcreate opentest /dev/
  No device found for /dev/.
+ vgextend opentest /dev/vdb /dev/ /dev/ -y
  No device found for /dev/.
  No device found for /dev/.
  Command requires all devices to be found.
+ LOG_INFO 'Loading data is complete!'
+ message='Loading data is complete!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Loading data is complete!'
Fri Apr 28 06:58:51 2023 - INFO  - Loading data is complete!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start executing testcase!'
+ message='Start executing testcase!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start executing testcase!'
Fri Apr 28 06:58:52 2023 - INFO  - Start executing testcase!
+ expect -c '
    set timeout 30
    log_file testlog
    spawn lvcreate --type raid1 -m 1 -n test --nosync -L 50MB opentest
    expect "*\[y/n\]*" {send "y\r"}
    expect eof
'
spawn lvcreate --type raid1 -m 1 -n test --nosync -L 50MB opentest
modprobe: FATAL: Module dm-raid not found in directory /lib/modules/6.1.8-3.oe2303.riscv64
y
  /usr/sbin/modprobe failed: 1
  raid1: Required device-mapper target(s) not detected in your kernel.
  Run `lvcreate --help' for more information.
+ grep -iE 'error|fail|while executing' testlog
  /usr/sbin/modprobe failed: 1
+ CHECK_RESULT 0 1
+ actual_result=0
+ expect_result=1
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 1x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_lvm_cling.sh line 39'
+ message='oe_test_storage_lvm_cling.sh line 39'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_lvm_cling.sh line 39'
Fri Apr 28 06:58:54 2023 - ERROR - oe_test_storage_lvm_cling.sh line 39
+ '[' 0 -eq 1 ']'
+ return 0
+ lvs -a -o +devices
+ CHECK_RESULT 0
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ lvextend --alloc cling -L +50MB opentest/test
  Volume group "opentest" not found
  Cannot process volume group opentest
+ CHECK_RESULT 5
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_lvm_cling.sh line 43'
+ message='oe_test_storage_lvm_cling.sh line 43'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_lvm_cling.sh line 43'
Fri Apr 28 06:58:55 2023 - ERROR - oe_test_storage_lvm_cling.sh line 43
+ '[' 0 -eq 1 ']'
+ return 0
+ lvs -a -o +devices
+ CHECK_RESULT 0
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ LOG_INFO 'End of testcase execution!'
+ message='End of testcase execution!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End of testcase execution!'
Fri Apr 28 06:58:56 2023 - INFO  - End of testcase execution!
+ CASE_RESULT 0
+ case_re=0
+ test -z 2
+ test 2 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Fri Apr 28 06:58:57 2023 - ERROR - failed to execute the case.
+ exit 2
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Fri Apr 28 06:58:58 2023 - INFO  - start environment cleanup.
+ rm -rf testlog
+ vgremove -y opentest
  Volume group "opentest" not found
  Cannot process volume group opentest
+ pvremove /dev/ /dev/vdb /dev/ /
  No device found for /dev/.
  No device found for /dev/.
  No device found for /.
  No PV found on device /dev/vdb.
+ LOG_INFO 'Finish environment cleanup.'
+ message='Finish environment cleanup.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup.'
Fri Apr 28 06:58:59 2023 - INFO  - Finish environment cleanup.
