+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the database config.'
+ message='Start to prepare the database config.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the database config.'
Wed May  3 04:47:02 2023 - INFO  - Start to prepare the database config.
+ test -d /lost+found
+ [[ 1 -eq 1 ]]
+ LOG_INFO '/lost+found doesn'\''t exist, no need to check.'
+ message='/lost+found doesn'\''t exist, no need to check.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message '/lost+found doesn'\''t exist, no need to check.'
Wed May  3 04:47:02 2023 - INFO  - /lost+found doesn't exist, no need to check.
+ return 0
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Wed May  3 04:47:02 2023 - INFO  - Start to run test.
+ ls -l /lost+found
+ grep 'total 0'
ls: cannot access '/lost+found': No such file or directory
+ CHECK_RESULT 1 0 0 'check /lost+found directory failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='check /lost+found directory failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'check /lost+found directory failed.'
+ LOG_ERROR 'check /lost+found directory failed.'
+ message='check /lost+found directory failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'check /lost+found directory failed.'
Wed May  3 04:47:03 2023 - ERROR - check /lost+found directory failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_dir_access_lostfound.sh line 36'
+ message='oe_test_FSIO_dir_access_lostfound.sh line 36'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_dir_access_lostfound.sh line 36'
Wed May  3 04:47:03 2023 - ERROR - oe_test_FSIO_dir_access_lostfound.sh line 36
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Wed May  3 04:47:03 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 1
+ test 1 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Wed May  3 04:47:03 2023 - ERROR - failed to execute the case.
+ exit 1
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Wed May  3 04:47:04 2023 - INFO  - Start to restore the test environment.
+ export LANG=
+ LANG=
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Wed May  3 04:47:04 2023 - INFO  - End to restore the test environment.
