+ source ../common/common_lib.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environmental preparation.'
+ message='Start environmental preparation.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start environmental preparation.'
Thu Jun 22 09:27:10 2023 - INFO  - Start environmental preparation.
+ DNF_INSTALL 'hadoop-3.1-hdfs java-1.8.0-openjdk'
+ pkgs='hadoop-3.1-hdfs java-1.8.0-openjdk'
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs 'hadoop-3.1-hdfs java-1.8.0-openjdk' --node 1 --tempfile ''
+ tmpfile2='Error: Unable to find a match: hadoop-3.1-hdfs'
+ '[' -z '' ']'
+ tmpfile='Error: Unable to find a match: hadoop-3.1-hdfs'
+ echo 'export JAVA_HOME=/usr/lib/jvm/jre'
+ sed -i '/Group=hadoop/a SuccessExitStatus=143' /usr/lib/systemd/system/hadoop-namenode.service
sed: can't read /usr/lib/systemd/system/hadoop-namenode.service: No such file or directory
+ systemctl daemon-reload
+ expect
spawn sudo -u hdfs hdfs namenode -format
sudo: unknown user hdfs
sudo: error initializing audit plugin sudoers_audit
expect: spawn id exp3 not open
    while executing
"expect eof"
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Thu Jun 22 09:27:44 2023 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start testing...'
+ message='Start testing...'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start testing...'
Thu Jun 22 09:27:45 2023 - INFO  - Start testing...
+ test_execution hadoop-namenode.service
+ service=hadoop-namenode.service
++ date '+%Y-%m-%d %T'
+ log_time='2023-06-22 09:27:45'
+ test_restart hadoop-namenode.service
+ service=hadoop-namenode.service
+ systemctl restart hadoop-namenode.service
Failed to restart hadoop-namenode.service: Unit hadoop-namenode.service not found.
+ CHECK_RESULT 5 0 0 'hadoop-namenode.service restart failed'
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log='hadoop-namenode.service restart failed'
+ exit_mode=0
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n 'hadoop-namenode.service restart failed'
+ LOG_ERROR 'hadoop-namenode.service restart failed'
+ message='hadoop-namenode.service restart failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'hadoop-namenode.service restart failed'
Thu Jun 22 09:27:46 2023 - ERROR - hadoop-namenode.service restart failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 34'
+ message='../common/common_lib.sh line 34'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 34'
Thu Jun 22 09:27:47 2023 - ERROR - ../common/common_lib.sh line 34
+ '[' 0 -eq 1 ']'
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status hadoop-namenode.service
+ grep 'Active: active'
Unit hadoop-namenode.service could not be found.
+ CHECK_RESULT 1 0 0 'hadoop-namenode.service restart failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='hadoop-namenode.service restart failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'hadoop-namenode.service restart failed'
+ LOG_ERROR 'hadoop-namenode.service restart failed'
+ message='hadoop-namenode.service restart failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'hadoop-namenode.service restart failed'
Thu Jun 22 09:27:53 2023 - ERROR - hadoop-namenode.service restart failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 37'
+ message='../common/common_lib.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 37'
Thu Jun 22 09:27:54 2023 - ERROR - ../common/common_lib.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ systemctl stop hadoop-namenode.service
Failed to stop hadoop-namenode.service: Unit hadoop-namenode.service not loaded.
+ CHECK_RESULT 5 0 0 'hadoop-namenode.service stop failed'
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log='hadoop-namenode.service stop failed'
+ exit_mode=0
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n 'hadoop-namenode.service stop failed'
+ LOG_ERROR 'hadoop-namenode.service stop failed'
+ message='hadoop-namenode.service stop failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'hadoop-namenode.service stop failed'
Thu Jun 22 09:27:54 2023 - ERROR - hadoop-namenode.service stop failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 39'
+ message='../common/common_lib.sh line 39'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 39'
Thu Jun 22 09:27:55 2023 - ERROR - ../common/common_lib.sh line 39
+ '[' 0 -eq 1 ']'
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status hadoop-namenode.service
+ grep 'Active: inactive'
Unit hadoop-namenode.service could not be found.
+ CHECK_RESULT 1 0 0 'hadoop-namenode.service stop failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='hadoop-namenode.service stop failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'hadoop-namenode.service stop failed'
+ LOG_ERROR 'hadoop-namenode.service stop failed'
+ message='hadoop-namenode.service stop failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'hadoop-namenode.service stop failed'
Thu Jun 22 09:28:02 2023 - ERROR - hadoop-namenode.service stop failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 42'
+ message='../common/common_lib.sh line 42'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 42'
Thu Jun 22 09:28:02 2023 - ERROR - ../common/common_lib.sh line 42
+ '[' 0 -eq 1 ']'
+ return 0
+ systemctl start hadoop-namenode.service
Failed to start hadoop-namenode.service: Unit hadoop-namenode.service not found.
+ CHECK_RESULT 5 0 0 'hadoop-namenode.service start failed'
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log='hadoop-namenode.service start failed'
+ exit_mode=0
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n 'hadoop-namenode.service start failed'
+ LOG_ERROR 'hadoop-namenode.service start failed'
+ message='hadoop-namenode.service start failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'hadoop-namenode.service start failed'
Thu Jun 22 09:28:03 2023 - ERROR - hadoop-namenode.service start failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 44'
+ message='../common/common_lib.sh line 44'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 44'
Thu Jun 22 09:28:04 2023 - ERROR - ../common/common_lib.sh line 44
+ '[' 0 -eq 1 ']'
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ grep 'Active: active'
+ systemctl status hadoop-namenode.service
Unit hadoop-namenode.service could not be found.
+ CHECK_RESULT 1 0 0 'hadoop-namenode.service start failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='hadoop-namenode.service start failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'hadoop-namenode.service start failed'
+ LOG_ERROR 'hadoop-namenode.service start failed'
+ message='hadoop-namenode.service start failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'hadoop-namenode.service start failed'
Thu Jun 22 09:28:10 2023 - ERROR - hadoop-namenode.service start failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 47'
+ message='../common/common_lib.sh line 47'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 47'
Thu Jun 22 09:28:11 2023 - ERROR - ../common/common_lib.sh line 47
+ '[' 0 -eq 1 ']'
+ return 0
+ test_enabled hadoop-namenode.service
+ service=hadoop-namenode.service
++ systemctl is-enabled hadoop-namenode.service
Failed to get unit file state for hadoop-namenode.service: No such file or directory
+ state=
+ '[' '' == enabled ']'
+ '[' '' == disabled ']'
+ '[' '' == masked ']'
+ '[' '' == static ']'
+ LOG_INFO 'Unit is indirect, ignoring.'
+ message='Unit is indirect, ignoring.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Unit is indirect, ignoring.'
Thu Jun 22 09:28:12 2023 - INFO  - Unit is indirect, ignoring.
+ journalctl --since '2023-06-22 09:27:45' -u hadoop-namenode.service
+ grep -i 'fail\|error'
+ grep -v -i 'DEBUG\|INFO\|WARNING'
+ CHECK_RESULT 1 0 1 'There is an error message for the log of hadoop-namenode.service'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='There is an error message for the log of hadoop-namenode.service'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ test_reload hadoop-namenode.service
+ service=hadoop-namenode.service
+ systemctl start hadoop-namenode.service
Failed to start hadoop-namenode.service: Unit hadoop-namenode.service not found.
+ systemctl reload hadoop-namenode.service
+ grep 'Job type reload is not applicable'
+ CHECK_RESULT 1 0 0 'Job type reload is not applicable for unit hadoop-namenode.service'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Job type reload is not applicable for unit hadoop-namenode.service'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Job type reload is not applicable for unit hadoop-namenode.service'
+ LOG_ERROR 'Job type reload is not applicable for unit hadoop-namenode.service'
+ message='Job type reload is not applicable for unit hadoop-namenode.service'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Job type reload is not applicable for unit hadoop-namenode.service'
Thu Jun 22 09:28:13 2023 - ERROR - Job type reload is not applicable for unit hadoop-namenode.service
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 91'
+ message='../common/common_lib.sh line 91'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 91'
Thu Jun 22 09:28:13 2023 - ERROR - ../common/common_lib.sh line 91
+ '[' 0 -eq 1 ']'
+ return 0
+ systemctl status hadoop-namenode.service
+ grep 'Active: active'
Unit hadoop-namenode.service could not be found.
+ systemctl status hadoop-namenode.service
+ grep 'inactive (dead)'
Unit hadoop-namenode.service could not be found.
+ return 1
+ LOG_INFO 'Finish test!'
+ message='Finish test!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish test!'
Thu Jun 22 09:28:14 2023 - INFO  - Finish test!
+ CASE_RESULT 0
+ case_re=0
+ test -z 7
+ test 7 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Thu Jun 22 09:28:15 2023 - ERROR - failed to execute the case.
+ exit 7
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Thu Jun 22 09:28:16 2023 - INFO  - start environment cleanup.
+ sed -i '/export JAVA_HOME=\/usr\/lib\/jvm\/jre/d' /usr/libexec/hadoop-layout.sh
+ sed -i /SuccessExitStatus=143/d /usr/lib/systemd/system/hadoop-namenode.service
sed: can't read /usr/lib/systemd/system/hadoop-namenode.service: No such file or directory
+ systemctl daemon-reload
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z Error: Unable to find a match: hadoop-3.1-hdfs ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile 'Error: Unable to find a match: hadoop-3.1-hdfs'
Traceback (most recent call last):
  File "/root/mugen/libs/locallibs/rpm_manage.py", line 173, in <module>
    exitcode = rpm_remove(args.node, args.pkgs, args.tempfile)
  File "/root/mugen/libs/locallibs/rpm_manage.py", line 144, in rpm_remove
    with open(tmpfile, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'Error: Unable to find a match: hadoop-3.1-hdfs'
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'Finish environment cleanup!'
+ message='Finish environment cleanup!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup!'
Thu Jun 22 09:28:24 2023 - INFO  - Finish environment cleanup!
